name: Update browser-specs
on:
  workflow_dispatch:
  schedule:
    # https://crontab.guru/#5_8_*_*_*
    - cron: "5 8 * * *"

# Conditional runs
# https://stackoverflow.com/a/61832535/2460034
jobs:
  update-webref:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '15'

      - run: npm ci
      - run: npm i browser-specs@latest
      - id: git-diff
        run: git diff --quiet HEAD
        continue-on-error: true
      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || git commit -m "chore(package): update browser-specs"
          git push

